services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: desafio-tecnico:latest
    container_name: desafio-tecnico
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PHX_SERVER: "true"
    ports:
      - "${PORT:-4000}:${PORT:-4000}"
    volumes:
      - ./data:/etc/desafio_tecnico
